"""add table quotekeyword

Revision ID: 54e4c66d9c90
Revises: 30671560f067
Create Date: 2022-08-17 17:03:14.428966+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e4c66d9c90'
down_revision = '30671560f067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotekeyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['quote'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quote_keyword')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_keyword',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quote', sa.INTEGER(), nullable=True),
    sa.Column('keyword', sa.INTEGER(), nullable=True),
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('keyword_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['keyword'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['quote'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quotekeyword')
    # ### end Alembic commands ###
